/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.DAOstudent;
import controller.Studentcontroler;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.JDBCUtil;
import model.Student;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JRadioButton;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public class studenView extends javax.swing.JFrame {

    /**
     * Creates new form studenView
     */
    public studenView() {
        myinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editStudent = new javax.swing.JDialog();
        studentIdJ = new javax.swing.JTextField();
        nameSJ = new javax.swing.JTextField();
        dateSJ = new javax.swing.JTextField();
        classSJ = new javax.swing.JTextField();
        adressSJ = new javax.swing.JTextField();
        majorSJ = new javax.swing.JTextField();
        sdtSJ = new javax.swing.JTextField();
        emailSJ = new javax.swing.JTextField();
        passSJ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnCapNhatSJ = new javax.swing.JButton();
        btnHuySJ = new javax.swing.JButton();
        btnNamSJ = new javax.swing.JRadioButton();
        btnNuSJ = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnNam = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnNu = new javax.swing.JRadioButton();
        tDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tAdress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tClass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tSdt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnTheoMsv = new javax.swing.JRadioButton();
        btnTheoTen = new javax.swing.JRadioButton();
        BtnTheoLop = new javax.swing.JRadioButton();
        tTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        cbMajor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        jLabel12.setText("Mã sinh viên");

        jLabel13.setText("Tên sinh viên");

        jLabel14.setText("Giới tính");

        jLabel15.setText("Ngày sinh");

        jLabel16.setText("Lớp");

        jLabel17.setText("Địa chỉ");

        jLabel18.setText("Chuyên ngành");

        jLabel19.setText("SDT");

        jLabel20.setText("Email");

        jLabel21.setText("Mật khẩu");

        btnCapNhatSJ.setText("Cập nhật");

        btnHuySJ.setText("Hủy");

        btnNamSJ.setText("Nam");

        btnNuSJ.setText("Nữ");

        javax.swing.GroupLayout editStudentLayout = new javax.swing.GroupLayout(editStudent.getContentPane());
        editStudent.getContentPane().setLayout(editStudentLayout);
        editStudentLayout.setHorizontalGroup(
            editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStudentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(49, 49, 49)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(studentIdJ)
                        .addComponent(nameSJ)
                        .addComponent(dateSJ)
                        .addComponent(classSJ)
                        .addComponent(adressSJ)
                        .addComponent(majorSJ)
                        .addComponent(sdtSJ)
                        .addComponent(emailSJ)
                        .addComponent(passSJ, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(editStudentLayout.createSequentialGroup()
                        .addComponent(btnNamSJ)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuSJ)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(editStudentLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnCapNhatSJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnHuySJ)
                .addGap(74, 74, 74))
        );
        editStudentLayout.setVerticalGroup(
            editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStudentLayout.createSequentialGroup()
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editStudentLayout.createSequentialGroup()
                        .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentIdJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(nameSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNamSJ)
                                .addComponent(btnNuSJ)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdtSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhatSJ)
                    .addComponent(btnHuySJ))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tìm kiếm");

        jLabel2.setText("Thông tin sinh viên");

        jLabel3.setText("Mã SV");

        jLabel4.setText("Tên SV");

        btnNam.setText("Nam");
        btnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tính");

        btnNu.setText("Nữ");
        btnNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Địa chỉ");

        jLabel8.setText("Lớp");

        jLabel9.setText("Email");

        jLabel10.setText("SDT");

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Tên  SV", "Giới tính", "Ngày sinh","Lớp","Địa chỉ","Chuyên ngành","SDT","Email","Password"
            }
        ));
        jScrollPane1.setViewportView(tbStudent);

        btnThem.setText("Thêm");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");

        btnLammoi.setText("Làm mới");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTheoMsv.setText("Tìm kiếm theo mã sinh viên");

        btnTheoTen.setText("Tìm kiếm theo tên");

        BtnTheoLop.setText("Tìm kiếm theo lớp");

        btnTim.setText("Tìm");

        cbMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Công nghệ thông tin","An toàn thông tin","Hệ thống thông tin","Kế toán","Trí tuệ nhân tạo","Quản trị","Âm nhạc"}));
        cbMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMajorActionPerformed(evt);
            }
        });

        jLabel11.setText("Chuyên ngành");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnNu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(tId))
                            .addComponent(btnNam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(37, 37, 37)
                                .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(30, 30, 30)
                                    .addComponent(tAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tClass, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTheoLop)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTheoTen)
                                    .addComponent(btnTheoMsv, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tTimKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTim))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(btnThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLammoi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThoat)))
                                .addGap(0, 113, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTheoMsv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTheoTen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnTheoLop)
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(tAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(tClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNu)
                        .addComponent(jLabel9)
                        .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(btnNam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(tSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnLammoi)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThem)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getCbMajor() {
        return cbMajor;
    }

    private void btnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNamActionPerformed

    private void btnNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMajorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studenView().setVisible(true);
            }
        });
    }
    public ButtonGroup buttonGrgendenr=new ButtonGroup();
  public ButtonGroup buttonGrSearch=new ButtonGroup();

    public JButton getBtnLammoi() {
        return btnLammoi;
    }

    public void setBtnLammoi(JButton btnLammoi) {
        this.btnLammoi = btnLammoi;
    }

    public JButton getBtnSua() {
        return btnSua;
    }

    public void setBtnSua(JButton btnSua) {
        this.btnSua = btnSua;
    }

    public JButton getBtnThoat() {
        return btnThoat;
    }

    public void setBtnThoat(JButton btnThoat) {
        this.btnThoat = btnThoat;
    }

    public JButton getBtnTim() {
        return btnTim;
    }

    public void setBtnTim(JButton btnTim) {
        this.btnTim = btnTim;
    }

    public JButton getBtnXoa() {
        return btnXoa;
    }

    public void setBtnXoa(JButton btnXoa) {
        this.btnXoa = btnXoa;
    }

    public JTextField gettAdress() {
        return tAdress;
    }

    public void settAdress(JTextField tAdress) {
        this.tAdress = tAdress;
    }

    public JTextField gettClass() {
        return tClass;
    }

    public void settClass(JTextField tClass) {
        this.tClass = tClass;
    }

    public JTextField gettDate() {
        return tDate;
    }

    public void settDate(JTextField tDate) {
        this.tDate = tDate;
    }

    public JTextField gettEmail() {
        return tEmail;
    }

    public void settEmail(JTextField tEmail) {
        this.tEmail = tEmail;
    }

    public JTextField gettId() {
        return tId;
    }

    public void settId(JTextField tId) {
        this.tId = tId;
    }

    public JTextField gettName() {
        return tName;
    }

    public void settName(JTextField tName) {
        this.tName = tName;
    }

    public JTextField gettSdt() {
        return tSdt;
    }

    public void settSdt(JTextField tSdt) {
        this.tSdt = tSdt;
    }

    public JTextField gettTimKiem() {
        return tTimKiem;
    }

    public void settTimKiem(JTextField tTimKiem) {
        this.tTimKiem = tTimKiem;
    }
       

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnTheoLop;
    private javax.swing.JTextField adressSJ;
    private javax.swing.JButton btnCapNhatSJ;
    private javax.swing.JButton btnHuySJ;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNamSJ;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JRadioButton btnNuSJ;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JRadioButton btnTheoMsv;
    private javax.swing.JRadioButton btnTheoTen;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMajor;
    private javax.swing.JTextField classSJ;
    private javax.swing.JTextField dateSJ;
    private javax.swing.JDialog editStudent;
    private javax.swing.JTextField emailSJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField majorSJ;
    private javax.swing.JTextField nameSJ;
    private javax.swing.JTextField passSJ;
    private javax.swing.JTextField sdtSJ;
    private javax.swing.JTextField studentIdJ;
    private javax.swing.JTextField tAdress;
    private javax.swing.JTextField tClass;
    private javax.swing.JTextField tDate;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tSdt;
    private javax.swing.JTextField tTimKiem;
    private javax.swing.JTable tbStudent;
    // End of variables declaration//GEN-END:variables
    Studentcontroler stc=new Studentcontroler(this);
 public ArrayList<Student> dsSV;

private void myinitComponents() {
    initComponents();
    buttonGrgendenr.add(btnNam);
    buttonGrgendenr.add(btnNu);
    buttonGrSearch.add(btnTheoTen);
    buttonGrSearch.add(btnTheoMsv);
    buttonGrSearch.add(BtnTheoLop);
    btnLammoi.addActionListener(stc);
    btnThem.addActionListener(stc);
    btnSua.addActionListener(stc);
    btnXoa.addActionListener(stc);
    btnThoat.addActionListener(stc);
    btnTim.addActionListener(stc);
    dsSV = new ArrayList<Student>();
    editStudent.setBounds(150, 150, 450, 450);
    btnCapNhatSJ.addActionListener(stc);
    btnHuySJ.addActionListener(stc);
    ArrayList<Student> dsSV=DAOstudent.getInstance().selectAll();
    capnhatthongtin(dsSV);
}

    public ButtonGroup getButtonGrgendenr() {
        return buttonGrgendenr;
    }

   public  void reset(){
        tAdress.setText("");
        tClass.setText("");
        tDate.setText("");
        tEmail.setText("");
        tId.setText("");
        tName.setText("");
        tSdt.setText("");
        tTimKiem.setText("");
        buttonGrSearch.clearSelection();
        buttonGrgendenr.clearSelection();
        cbMajor.setSelectedIndex(-1);
         ArrayList<Student> dsSV=DAOstudent.getInstance().selectAll();
        capnhatthongtin(dsSV);
        
        
        
    }

    public JTextField getAdressSJ() {
        return adressSJ;
    }

    public JButton getBtnCapNhatSJ() {
        return btnCapNhatSJ;
    }

    public JButton getBtnHuySJ() {
        return btnHuySJ;
    }

    public JTextField getClassSJ() {
        return classSJ;
    }

    public JTextField getDateSJ() {
        return dateSJ;
    }

    public JTextField getEmailSJ() {
        return emailSJ;
    }

    public JTextField getMajorSJ() {
        return majorSJ;
    }

    public JTextField getNameSJ() {
        return nameSJ;
    }

    public JTextField getPassSJ() {
        return passSJ;
    }

    public JTextField getSdtSJ() {
        return sdtSJ;
    }

    public JTextField getStudentIdJ() {
        return studentIdJ;
    }
   
    public JButton getBtnThem() {
        return btnThem;
    }

    public JRadioButton getBtnNam() {
        return btnNam;
    }

    public JRadioButton getBtnNu() {
        return btnNu;
    }
   public void Delete(Student t){
       dsSV.remove(t);
       DAOstudent.getInstance().delete(t);
    
       
   }
  public void Insert(Student t) {
    dsSV.add(t);

    Connection c = null;
    try {
        c = JDBCUtil.getConnection();
        DAOstudent.getInstance().insert(t);

        SimpleDateFormat displaySdf = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = displaySdf.format(t.getDob());

        DefaultTableModel md = (DefaultTableModel) tbStudent.getModel();
        md.addRow(new Object[]{
                t.getStudentId(), t.getName(), t.getGender(), formattedDate, t.getClassRoon(),
                t.getAddress(), t.getMajor(), t.getPhone(), t.getEmail(), t.getPassword(),
        });
    } catch (Exception e) {
        e.printStackTrace();
        // Handle or log the SQL exception appropriately
    } finally {
        
        if (c != null) {
            try {
                c.close();
            } catch (Exception e) {
                e.printStackTrace();
                // Handle or log the SQL exception appropriately
            }
        }
    }
}   

    public JDialog getEditStudent() {
        return editStudent;
    }

    public JTable getTbStudent() {
        return tbStudent;
    }

    public JRadioButton getBtnNamSJ() {
        return btnNamSJ;
    }

    public JRadioButton getBtnNuSJ() {
        return btnNuSJ;
    }
  

   public void capnhatthongtin(ArrayList<Student> dsSV){
       DefaultTableModel md=(DefaultTableModel) tbStudent.getModel();
       md.setRowCount(0);
       
       for(Student t: dsSV){
        md.addRow(new Object[]{
        t.getStudentId(), t.getName(),t.getGender(), t.getDob(), t.getClassRoon(), t.getAddress(), t.getMajor(),t.getPhone(),t.getEmail(),t.getPassword(),
    });
           
       }
   }
   public void timThongtinId(Student st){
       DefaultTableModel model = (DefaultTableModel)tbStudent.getModel();
        model.setRowCount(0);
        ArrayList<Student> rs=DAOstudent.getInstance().selectByID(st);
        for(Student t: rs){
        model.addRow(new Object[]{
        t.getStudentId(), t.getName(),t.getGender(), t.getDob(), t.getClassRoon(), t.getAddress(), t.getMajor(),t.getPhone(),t.getEmail(),t.getPassword(),
       
   });
   }
   }
   
     public void timThongtinName(Student st){
       DefaultTableModel model = (DefaultTableModel)tbStudent.getModel();
        model.setRowCount(0);
        ArrayList<Student> rs=DAOstudent.getInstance().selectByName(st);
        for(Student t: rs){
        model.addRow(new Object[]{
        t.getStudentId(), t.getName(),t.getGender(), t.getDob(), t.getClassRoon(), t.getAddress(), t.getMajor(),t.getPhone(),t.getEmail(),t.getPassword(),
       
   });
   }
   }
        public void timThongtinClass(Student st){
       DefaultTableModel model = (DefaultTableModel)tbStudent.getModel();
        model.setRowCount(0);
        ArrayList<Student> rs=DAOstudent.getInstance().selectByClass(st);
        for(Student t: rs){
        model.addRow(new Object[]{
        t.getStudentId(), t.getName(),t.getGender(), t.getDob(), t.getClassRoon(), t.getAddress(), t.getMajor(),t.getPhone(),t.getEmail(),t.getPassword(),
       
   });
   }
   }

    public JRadioButton getBtnTheoLop() {
        return BtnTheoLop;
    }

    public JRadioButton getBtnTheoMsv() {
        return btnTheoMsv;
    }

    public JRadioButton getBtnTheoTen() {
        return btnTheoTen;
    }
   
   

    
}



